### ISSUE TITLE
cosine is not dividing by norm of each vector, not norm of the dot product ?

### ISSUE THREAD

**Issue by christopher5106** [distillpub/post--activation-atlas#12]
It looks like the formula 
\frac{(h_{x,y} \cdot v)^{n+1}}{(||h_{x,y} \cdot v|| \cdot ||v||)^{n}} 
 should be 
\frac{(h_{x,y} \cdot v)^{n+1}}{(||h_{x,y}|| \cdot ||v||)^{n}} 
​

**Comment by ludwigschubert** [comment]
@christopher5106 thanks for catching this! :-) You're unambiguously right.

**Comment by ludwigschubert** [comment]
Fixed in 20024d4! May take a while to be deployed, though. Thanks again!
