### ISSUE TITLE
Scrolling labels inside class visualization

### ISSUE THREAD

**Issue by ncammarata** [distillpub/post--activation-atlas#25]
This is an extremely tiny detail, but inside the class visualization figure I'm able to scroll individual class labels rather than having scroll move the whole list of labels.

![image](https://user-images.githubusercontent.com/204989/58130820-e1e87500-7bd1-11e9-9905-803754974663.png)

In this example I scrolled the word "fireboat" slightly.

If you add `overflow-y: hidden;` to `label` this fixes it, but I'm not sure if this is the best solution

**Comment by ludwigschubert** [comment]
I have a hard time reproducing—do you maybe know which browser and viewport width this was?

I'd assume this could happen due to the opacity: 0 `input` tag. @shancarter do you think it could be set to display: none instead?

**Comment by ncammarata** [comment]
My browser is `Chrome 74.0.3729.157` and I get it for all browser widths. I'm not sure what you mean by "viewport width" but the meta[name=viewport] tag contains `<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by ludwigschubert** [comment]
@ncammarata Nick, I just took another look and couldn't reproduce the issue—please let me know if you (or anyone else) comes across this again!

Tacit knowledge: I believe there were hidden input elements (radio inputs?) in those list items, which might have broken onto a second line as their invisibility was achieved by setting opacity to 0. I'll check if I didn't already make a change there, such as forcing `position: absolute`, or some other trick to remove the input element from the flow.
