### ISSUE TITLE
Editorial comments

### ISSUE THREAD

**Issue by phillipi** [distillpub/post--activation-atlas#6]
Thank you for thoroughly addressing the concerns of the reviewers. I am happy to advocate acceptance of the article. Congratulations on a very cool piece of work!

Although I'm happy accepting the article as is, here are a few suggestions for minor revisions to improve it further:

A few ideas in the article are not fully self-contained. They are explained in other distill posts but I think it would be good to restate the justification in this article. Two jumped out to me:
1. Why does it make sense to use the dot product (or the modified version of this) as the objective for feature visualization of a single patch’s activations? The confusing thing for me is that if one used a distance metric like Euclidean, a global minimum would be the exact input patch. The “why visualize by optimization?” section of the feature visualization article gives some good intuition that could be ported over here.
2. I think it would be useful to add a short discussion of the pros and cons of the activation atlas compared to a nonparametric version of it (like Karpathy's CNN codes). Again, reference can be made to the “why visualize by optimization” arguments. The article states: "Showing which images the model sees as similar does help us infer some ideas about what features the network is responding to, but feature visualization makes those connections much more explicit." Can this be explained in more detail? Currently understanding this point requires reading past work.

A few more minor issues:

1. “simple combinations of neurons” link doesn’t work in my browser (Chrome)
2. Typo here: “Each layer successively builds of the previous layers”
3. “how much each neuron fired for each path separately” — “path”—>”patch”?
5. “rate at which increasing the neuron effects the logit” — “effects” —> “affects”
6. “farily” —> “fairly”
7. Some of the “Try in a notebook” links don’t work for me
8. The concept “a palette of concepts rather than colors” is quite similar to the the [GANpaint tool](gandissect.csail.mit.edu), perhaps worth referencing

**Comment by ludwigschubert** [comment]
Links are fixed in public version. :-) @shancarter do you feel we addressed the major points @phillipi raised in @colah 's rewrites of those two sections, or should we leave this issue open for now?
